export const mutators: { [x: string]: string[] } = {
  game_mode: [
    "Soccer",
    "Hoops",
    "Dropshot",
    "Hockey",
    "Rumble",
    "Heatseeker",
    "Gridiron",
    "Knockout",
  ],
  match_length: ["Five Minutes", "Ten Minutes", "Twenty Minutes", "Unlimited"],
  max_score: [
    "Default",
    "One Goal",
    "Three Goals",
    "Five Goals",
    "Seven Goals",
    "Unlimited",
  ],
  multi_ball: ["One", "Two", "Four", "Six"],
  overtime: ["Unlimited", "Five Max First Score", "Five Max Random Team"],
  series_length: [
    "Unlimited",
    "Three Games",
    "Five Games",
    "Seven Games",
  ],
  game_speed: ["Default", "Slo Mo", "Time Warp"],
  ball_max_speed: ["Default", "Slow", "Fast", "Super Fast"],
  ball_type: [
    "Default",
    "Cube",
    "Puck",
    "Basketball",
    "Beachball",
    "Anniversary",
    "Haunted",
    "Ekin",
    "Spooky Cube",
  ],
  ball_weight: [
    "Default",
    "Light",
    "Heavy",
    "Super Light",
    "Curve Ball",
    "Beach Ball Curve",
    "Magnus FutBall",
  ],
  ball_size: ["Default", "Small", "Medium", "Large", "Gigantic"],
  ball_bounciness: ["Default", "Low", "High", "Super High", "Lowish"],
  boost_amount: [
    "Default",
    "Unlimited",
    "Slow Recharge",
    "Rapid Recharge",
    "None",
  ],
  rumble: [
    "None",
    "Default",
    "Slow",
    "Civilized",
    "Destruction Derby",
    "Spring Loaded",
    "Spikes Only",
    "Spike Rush",
    "Haunted Ball Beam",
    "Tactical",
    "Batman Rumble",
  ],
  boost_strength: ["1x", "1.5x", "2x", "5x", "10x"],
  gravity: ["Default", "Low", "High", "Super High", "Reverse"],
  demolish: [
    "Default",
    "Disabled",
    "Friendly Fire",
    "On Contact",
    "On Contact FF",
  ],
  respawn_time: [
    "Three Seconds",
    "Two Seconds",
    "One Second",
    "Disable Goal Reset",
  ],
  max_time: ["Default", "Eleven Minutes"],
  game_event: ["Default", "Haunted", "Rugby"],
  audio: ["Default", "Haunted"],
};
