export const mutators: { [x: string]: string[] } = {
  game_mode: [
    "Soccer",
    "Hoops",
    "Dropshot",
    "Hockey",
    "Rumble",
    "Heatseeker",
    "Gridiron",
    "Knockout",
  ],
  match_length: ["Five Minutes", "Ten Minutes", "Twenty Minutes", "Unlimited"],
  max_score: [
    "Default",
    "One Goal",
    "Three Goals",
    "Five Goals",
    "Seven Goals",
    "Unlimited",
  ],
  multi_ball: ["One", "Two", "Four", "Six"],
  overtime_option: [
    "Unlimited",
    "Five Max First Score",
    "Five Max Random Team",
  ],
  // This mutator does nothing
  // series_length_option: [
  //   "Unlimited",
  //   "Three Games",
  //   "Five Games",
  //   "Seven Games",
  // ],
  game_speed_option: ["Default", "Slo Mo", "Time Warp"],
  ball_max_speed_option: ["Default", "Slow", "Fast", "Super Fast"],
  ball_type_option: [
    "Default",
    "Cube",
    "Puck",
    "Basketball",
    "Beachball",
    "Anniversary",
    "Haunted",
    "Ekin",
    "Spooky Cube",
  ],
  ball_weight_option: [
    "Default",
    "Light",
    "Heavy",
    "Super Light",
    "Curve Ball",
    "Beach Ball Curve",
    "Magnus FutBall",
  ],
  ball_size_option: ["Default", "Small", "Medium", "Large", "Gigantic"],
  ball_bounciness_option: [
    "Default",
    "Low",
    "High",
    "Super High",
    "Lowish",
  ],
  boost_option: [
    "Default",
    "Unlimited",
    "Slow Recharge",
    "Rapid Recharge",
    "None",
  ],
  rumble_option: [
    "None",
    "Default",
    "Slow",
    "Civilized",
    "Destruction Derby",
    "Spring Loaded",
    "Spikes Only",
    "Spike Rush",
    "Haunted Ball Beam",
    "Tactical",
    "Batman Rumble",
  ],
  boost_strength_option: ["1x", "1.5x", "2x", "5x", "10x"],
  gravity_option: ["Default", "Low", "High", "Super High", "Reverse"],
  demolish_option: [
    "Default",
    "Disabled",
    "Friendly Fire",
    "On Contact",
    "On Contact FF",
  ],
  respawn_time_option: [
    "Three Seconds",
    "Two Seconds",
    "One Second",
    "Disable Goal Reset",
  ],
  max_time_option: ["Default", "Eleven Minutes"],
  game_event_option: ["Default", "Haunted", "Rugby"],
  audio_option: ["Default", "Haunted"],
};
