// biome-ignore format: keep consistent
export const MAPS_STANDARD = {
  "DFH Stadium": "Stadium_P",
  "Mannfield": "EuroStadium_P",
  "Champions Field": "cs_p",
  "Urban Central": "TrainStation_P",
  "Beckwith Park": "Park_P",
  "Utopia Coliseum": "UtopiaStadium_P",
  "Wasteland": "wasteland_s_p",
  "NeoTokyo": "NeoTokyo_Standard_P",
  "Aqua Dome": "Underwater_P",
  "Starbase Arc": "arc_standard_p",
  "Farmstead": "farm_p",
  "Salty Shores": "beach_P",
  "DFH Stadium (Stormy)": "Stadium_Foggy_P",
  "DFH Stadium (Day)": "stadium_day_p",
  "Mannfield (Stormy)": "EuroStadium_Rainy_P",
  "Mannfield (Night)": "EuroStadium_Night_P",
  "Champions Field (Day)": "cs_day_p",
  "Beckwith Park (Stormy)": "Park_Rainy_P",
  "Beckwith Park (Midnight)": "Park_Night_P",
  "Urban Central (Night)": "TrainStation_Night_P",
  "Urban Central (Dawn)": "TrainStation_Dawn_P",
  "Utopia Coliseum (Dusk)": "UtopiaStadium_Dusk_P",
  "DFH Stadium (Snowy)": "Stadium_Winter_P",
  "Mannfield (Snowy)": "eurostadium_snownight_p",
  "Utopia Coliseum (Snowy)": "UtopiaStadium_Snow_P",
  "Forbidden Temple": "CHN_Stadium_P",
  "Rivals Arena": "cs_hw_p",
  "Farmstead (Night)": "Farm_Night_P",
  "Salty Shores (Night)": "beach_night_p",
  "Neon Fields": "music_p",
  "DFH Stadium (Circuit)": "Stadium_Race_Day_P",
  "Deadeye Canyon": "Outlaw_P",
  "Starbase Arc (Aftermath)": "ARC_Darc_P",
  "Wasteland (Night)": "Wasteland_Night_S_P",
  "Forbidden Temple (Day)": "CHN_Stadium_Day_P",
  "Beckwith Park (Snowy)": "Park_Snowy_P",
  "Utopia Coliseum (Gilded)": "UtopiaStadium_Lux_P",
  "Sovereign Heights": "Street_P",
  "Forbidden Temple (Fire And Ice)": "fni_stadium_p",
  "Deadeye Canyon (Oasis)": "outlaw_oasis_p",
  "Estadio Vida (Dusk)": "ff_dusk_p",
  "Mannfield (Dusk)": "eurostadium_dusk_p",
  "Farmstead (Pitched)": "farm_grs_p",
  "Wasteland (Pitched)": "wasteland_grs_p",
  "NeoTokyo (Hacked)": "neotokyo_hax_p",
  "AquaDome (Shallows)": "Underwater_GRS_P",
  "Salty Shores (SaltyFest)": "Beach_Night_GRS_P",
  "Drift Woods": "Woods_P",
  "NeoTokyo (Arcade)": "NeoTokyo_Arcade_P",
  "Futura Garden": "UF_Day_P",
};

// biome-ignore format: keep consistent
export const MAPS_NON_STANDARD = {
  "Badlands": "Wasteland_P",
  "Badlands (Night)": "Wasteland_Night_P",
  "Tokyo Underpass": "NeoTokyo_P",
  "Arctagon": "ARC_P",
  "Pillars": "Labs_CirclePillars_P",
  "Cosmic": "Labs_Cosmic_V4_P",
  "Double Goal": "Labs_DoubleGoal_V2_P",
  "Octagon": "Labs_Octagon_02_P",
  "Underpass": "Labs_Underpass_P",
  "Utopia Retro": "Labs_Utopia_P",
  "Hoops (Dunk House)": "HoopsStadium_P",
  "DropShot (Core707)": "ShatterShot_P",
  "Throwback Stadium": "ThrowbackStadium_P",
  "Beckwith Park Gotham Night": "Park_Bman_P",
  "Urban Central (Haunted)": "Haunted_TrainStation_P",
  "Champions Field (NFL)": "BB_P",
  "Throwback Stadium (Snowy)": "ThrowbackHockey_p",
  "Basin": "Labs_Basin_P",
  "Corridor": "Labs_Corridor_P",
  "Loophole": "Labs_Holyfield_P",
  "Galleon": "Labs_Galleon_P",
  "Galleon (Retro)": "Labs_Galleon_Mast_P",
  "Hourglass": "Labs_PillarGlass_P",
  "Barricade": "Labs_PillarHeat_P",
  "Colossus": "Labs_PillarWings_P",
  "NeoTokyo (Comic)": "NeoTokyo_Toon_P",
  "Hoops (The Block)": "HoopsStreet_P",
  "Farmstead (Spooky)": "Farm_HW_P",
  "Champions Field (Nike FC)": "swoosh_p",
  "Farmstead (Upsidedown)": "farm_hw_p",
  "Quadron": "KO_Quadron_P",
  "Calavera": "KO_Calavera_P",
  "Carbon": "KO_Carbon_P",
};
